name: Build Android APK

on: [push]

jobs:
  build:
    name: Build Android APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
        
      - name: Setup java
        uses: actions/setup-java@v1
        with:
            java-version: 1.8

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 13.x

      - name: Install Cordova
        run: npm install -g cordova

      - name: Install Ionic
        run: npm install -g @ionic/cli
        
      - name: Install app dependencies
        run: npm install

      - name: Add Android platform
        run: ionic cordova platform add android@9
        working-directory: ./appEstadisticas/
          
      - name: Renombrar dx.jar
        run: mv /usr/local/lib/android/sdk/build-tools/31.0.0/lib/d8.jar /usr/local/lib/android/sdk/build-tools/31.0.0/lib/dx.jar
          
      - name: Renombrar dx
        run: mv /usr/local/lib/android/sdk/build-tools/31.0.0/d8 /usr/local/lib/android/sdk/build-tools/31.0.0/dx 
        
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
        
      - name: Build Android Dev APK
        run: ionic cordova build android
        working-directory: ./appEstadisticas/

      - name: Generate the Android App Bundle
        working-directory: ./platforms/android/
        run: ./gradlew bundle

    
